### ISSUE TITLE
MySQLException for MySQL >= 5.6.2

### ISSUE THREAD

**Issue by joe776** [linqs/psl#10]
`partition` has become a reserved word since MySQL 5.6.2, thus leading to an exception when PSL tries to create its tables.

https://dev.mysql.com/doc/refman/5.6/en/keywords.html#ftn.idm140367954831264

**Comment by puuj** [comment]
Hi! We encourage users to post to the psl-users Google group for technical questions:
https://groups.google.com/forum/#!forum/psl-users

As a quick answer, you can override the name of the partition column in the predicate table by setting the option rdbmsdatastore.partitioncolumn when creating the datastore.

**Comment by joe776** [comment]
You can... but the default is broken with newer versions of MySQL, so IMHO that should be changed in the code.

**Comment by puuj** [comment]
I agree, that's a good point. MySQL support is still sort of experimental, so we appreciate bughunters! I've created a new bug with a more descriptive name.

Still, in the future, we'd appreciate if you posted to the user group first, so that other people who encounter the problem will be able to learn from the discussion. It also helps us pinpoint the exact cause so the bug report is more detailed.
