### ISSUE TITLE
How big the model can be

### ISSUE THREAD

**Issue by omidb** [linqs/psl#18]
Hi,

I wanted to know if you have any estimates on size and time of models? I understand the complexity of model can affect everything but I was curious that how fast it is in the applications that you have used PSL?
Does it parallelize well if I run it on a big machine?

Thanks

**Comment by eriq-augustine** [comment]
Hey,

I have recently been working on some bench-marking applications for PSL:
https://github.com/eriq-augustine/psl-performance

Here are the results of the transitivity test using a disk-based database (times in ms).
The machine has an Intel i7-4790K (4 cores, 8 threads @ 4.00GHz) and 32GB ram.

Number of Users | Number of Ground Rules | Number of Runs | Total Time | Min Time | Max Time | Mean Time
--- | --- | --- | --- | --- | --- | ---
10 | 900 | 100 | 6721 | 60 | 143 | 67
22 | 10164 |  100 | 99748 | 739 | 1804 | 997
47 | 101614 | 50 | 2406492 | 33290 | 55012 | 48129
101 | 1020100 | 10 | 5767460 | 539431 | 613886 | 576746

PSL does parallelize well on larger machines.
The optimization process takes advantage of every core, and we are working on making sure other parts of PSL leverage all the cores properly.

Unfortunately, it is pretty hard to give any hard guarantees on performance since the performance of a PSL program depends on several things:
 - Number of ground rules
   - Which is dependent on the number of rules and amount of data
 - Complexity of rules
 - How easy the data is to optimize

The simple transitivity benchmark (results above) explores the number of ground rules, but not the complexity of each rule.
However at least with these simple rules, PSL can handle over a million ground rules in under 10 minutes.

As an aside, we should probably keep questions like this in the PSL Users group and keep the issues for bugs and enhancements:
https://groups.google.com/forum/#!forum/psl-users
