### ISSUE TITLE
Custom port and destination Postgres

### ISSUE THREAD

**Issue by prdx** [linqs/psl#261]
I am trying to look for it but I could not find it. At a glance, I don't see this is supported.

```
dbPath = parsedOptions.getOptionValue(CommandLineLoader.OPTION_DB_POSTGRESQL_NAME, CommandLineLoader.DEFAULT_POSTGRES_DB_NAME);

```

**Comment by eriq-augustine** [comment]
Yeah, looks like you can't add a custom host/port in the current configuration.

Off the cuff, my solution would be to load the host and port through config instead of constants:
https://github.com/linqs/psl/blob/master/psl-core/src/main/java/org/linqs/psl/database/rdbms/driver/PostgreSQLDriver.java#L73

So you could run it on the cli like:
```
./run.sh --postgres mydb -D postgres.host=myhost.com -D postgres.port=12345
```

Do you need any additional config between database name, host, and port?

**Comment by prdx** [comment]
Thanks for the tips! User and password would be great too. I understand from the doc, it says I should make the the `user` be able to access without password, but would be great if we can also provide it.

**Comment by eriq-augustine** [comment]
All right, the change is in for this:
https://github.com/linqs/psl/commit/b9283c094e7842c644c0a19c6b8b423b7873e8af

This adds the config options:
 - `postgres.host`
 - `postgres.port`
 - `postgres.user`
 - `postgres.password`

`postgres.password` will not be echoed in the logs.

If you can build locally, give it a try.
Otherwise, it will be out in the next canary build.

I'm going to close this issue, but we can reopen if anything comes up in your testing.
