### ISSUE TITLE
Running ADMM inference on a custom set of potentials

### ISSUE THREAD

**Issue by Lammatian** [linqs/psl#311]
Hello,

I was wondering if there is any simple way to run ADMM with a custom set of potentials. Say I don't want to use the potentials generated by PSL and instead plug in my own optimisation problem - would it be possible to somehow use the existing code? Or is it easier to write a custom solver based on the `optimize` function of [ADMMReasoner](https://github.com/linqs/psl/blob/master/psl-core/src/main/java/org/linqs/psl/reasoner/admm/ADMMReasoner.java) and the inference algorithm in the [HL-MRFs paper](https://arxiv.org/abs/1505.04406)?

Best,
Matt

**Comment by eriq-augustine** [comment]
No, we don't specifically support anything like that.
(We support the reverse using the [ExecutableReasoner](https://github.com/linqs/psl/blob/develop/psl-core/src/main/java/org/linqs/psl/reasoner/ExecutableReasoner.java).)

However, you could write custom code to do this (but it would probably be a decent amount of work).
The Term representations themselves are easy, but there is other infrastructure you would have to tap into.
(Like how Reasoners are not meant to be run outside of an InferenceApplication.)

The easiest option would probably be to use an off-the-shelf ADMM library.

(I'm going to close the issue, but we can keep talking about it.)

**Comment by Lammatian** [comment]
Hi Eriq,

Thanks for your reply. Are there any ADMM libraries that you know of and would recommend for such a task?

Best,
Matt

**Comment by eriq-augustine** [comment]
What language do you want to use?
@dickensc Do you have any suggestions?

**Comment by Lammatian** [comment]
Any of Python/C++/Java would be okay, I have no particular preference

**Comment by dickensc** [comment]
Hello, ADMM is a high-level framework that will have typically have specialized implementations. 
This is because the variable updates require solving subproblems that are combinations of your objective and constraints.

For this reason, you may find ADMM based solvers for specific classes of optimization problems but it is more common to implement the high-level ADMM algorithm yourself and use solvers for the subproblems.
Here is an example of this pattern in action: https://www.cvxpy.org/examples/applications/consensus_opt.html
I also recommend using CVX and its implementations in other languages in general. 

Here is a reference with details on ADMM and common modeling strategies: 
https://stanford.edu/~boyd/papers/pdf/admm_distr_stats.pdf

**Comment by Lammatian** [comment]
That's very helpful, thank you both!

**Comment by Lammatian** [comment]
Would the situation change if I wanted to run ADMM with my own set of ground rules? Say I want to do grounding differently from the way it is done in PSL but still want to use the ADMM inference on my set of rules. Is there a way to do that easily, or do I have to create the ground rules from ground up in the code and bypass the grounding steps?

**Comment by eriq-augustine** [comment]
Yes, if you want to create your own set of ground rules then you have to
create your own custom grounding procedures.
