### ISSUE TITLE
Outdated psl-examples reference

### ISSUE THREAD

**Issue by douglaz** [linqs/psl#35]
I don't know how to make a pull request for the wiki, but this is the diff of what needs to be fixed:
https://github.com/douglaz/psl/commit/2258d5fa591df1f5c922ffe50ebd1bb452830b47#diff-f1f3553dc11c900585081e4963f0bcdf

**Comment by eriq-augustine** [comment]
Hey Allan,

Thanks for the heads up.
I have made the changes in our development wiki:
https://github.com/eriq-augustine/psl/wiki/Using-the-CLI

Note that the master wiki (https://github.com/linqs/psl/wiki) is kept in step with the current stable build.
Because of github's limitation on branches of the wiki (even though the underlying storage is a repository), we have to host to different versions of the wiki on different repositories.
