### ISSUE TITLE
Aggressive Caching of Atoms

### ISSUE THREAD

**Issue by JackSullivan** [linqs/psl#9]
It looks like both `AtomCache` and `PersistedAtomManager` (which appear unavoidable on the code path, as `PersistedAtomManager` is called by `MPEInferencer` and `AtomCache` is a class that any implementation of `Database` must return) cache and never discard a large number of `Atom`s. In particular, `buildPersistedAtomCache` effectively loads the entire database into memory by calling `db.getAtom` on every possible set of values for each predicate (since `getAtom` caches all these values in the `AtomCache`).

I guess my issue/thought here is twofold. The first is, why bother with `PersistedAtomManager` when `getAtom` implementations are already backed by a cache? The second is, `AtomCache` should be a proper cache in the sense that it should discard old values and allow them to be garbage collected. As it is it seems that it isn't possible to perform inference on datasets that are too large to fit entirely in memory, which seems to defeat the purpose of having a system that is backed by a database.

I'm certainly willing to help out in terms of addressing these two issues if there is support from the team, but I'd like to know if there is an underlying rationale for things being the way they are before I dive in with a knife.

**Comment by JackSullivan** [comment]
Also, if I read through the code properly, it seems that neither `PersistedAtomManager` nor the interface that it implements `AtomManager` ever have any method calls made against them in the code.

**Comment by JackSullivan** [comment]
Never mind that last comment, I've found some usages, but my above point still stands.

**Comment by eriq-augustine** [comment]
Although this issue is pretty old, I will address it here.

You are correct that the PersistedAtomManager queries the database for all atoms and effectively holds a significant chunk of the database in memory.
It does this so that it can tell the difference between a true RandomVariableAtom that is backed by the database, and one that does not have a real value in the database and was created on the fly in a call to getAtom().
PSL has a stipulation that in non-lazy inference,  the full world of targets (ground atoms for open predicates) must be specified.
This behavior is to detect which targets have been fully specified, and which have not been.

To the second point about about proper caches.
The database holds a cache for all the atoms it has seen, so the PersistedAtomManager really just holds references to the RandomVariableAtoms that it has seen.

You are correct, that a database too large to fit into memory will be impossible to do inference on.
However, we find that we rarely (if ever) encounter this situation.
What we load in PSL is typically already a processed form or a raw dataset that only contains the information we need.
The big drain on memory are ground rules, rather than ground atoms; since ground rules are often created using a crossproduct of ground atoms.

On the technical side, there have been a good amount of changes to the database and atom managers since this issue.
The most topical being that buildPersistedAtomCache() has been changed to do a single query per predicate instead of one query per atom.

I am going to close this issue, but please feel free to take a look at the atom managers in the development fork and raise any new issues/concerns:
https://github.com/eriq-augustine/psl/blob/develop/psl-core/src/main/java/org/linqs/psl/database/atom/PersistedAtomManager.java
